# Generated by Django 4.2.10 on 2024-06-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
