# Generated by Django 3.2.14 on 2024-06-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_id_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_on',
            new_name='created',
        ),
    ]
