# Generated by Django 3.2.4 on 2024-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240630_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../option_yellow_yktljb', upload_to='images/'),
        ),
    ]
