# Generated by Django 4.2.10 on 2024-06-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0002_alter_market_address_alter_market_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='organizer',
        ),
        migrations.AddField(
            model_name='market',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
