# Generated by Django 4.2.10 on 2024-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_market_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='time',
            new_name='end',
        ),
        migrations.AddField(
            model_name='market',
            name='start',
            field=models.TimeField(default='12:00'),
        ),
    ]
