# Generated by Django 3.2.14 on 2024-06-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_rename_time_market_end_market_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='market',
            old_name='created_on',
            new_name='created',
        ),
    ]
