# Generated by Django 3.2.14 on 2024-06-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_attendance_attended_market'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_on',
            new_name='created',
        ),
    ]
