# Generated by Django 4.2.10 on 2024-06-12 16:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('track_list', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Used', 'Used')], default='Used', max_length=9)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
