# Generated by Django 4.2.10 on 2024-06-15 16:30

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('track_list', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Used', 'Used')], default='Used', max_length=9)),
                ('image', models.ImageField(default='../default_record_ibxfab', upload_to='images/')),
                ('released', models.IntegerField(blank=True, default=0, null=True)),
                ('uploader', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'db_table': 'records_record',
                'managed': True,
            },
        ),
    ]
