# Generated by Django 4.2.10 on 2024-06-13 15:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('track_list', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Used', 'Used')], default='Used', max_length=9)),
                ('image', models.ImageField(default='../default_record_ibxfab', upload_to='images/')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Vinyl_record',
        ),
    ]
