# Generated by Django 4.2.10 on 2024-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='released',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
