# Generated by Django 4.2.10 on 2024-06-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_author_record_artist_remove_record_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='uploader',
            new_name='advertiser',
        ),
    ]
