# Generated by Django 4.2.10 on 2024-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_uploader_record_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
