# Generated by Django 4.2.10 on 2024-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='contact',
            field=models.CharField(default='email: example@email.com', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(default='Stockholm', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.CharField(default='100 sek', max_length=9),
        ),
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('New', 'New'), ('Used', 'Used')], default='Good', max_length=9),
        ),
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.CharField(choices=[('Alternative Rock', 'Alternative Rock'), ('Bachata', 'Bachata'), ('Black Metal', 'Black Metal'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Dance', 'Dance'), ('Death Metal', 'Death Metal'), ('Disco', 'Disco'), ('Dubstep', 'Dubstep'), ('Electronic', 'Electronic'), ('Emo', 'Emo'), ('Folk metal', 'Folk metal'), ('Folk music', 'Folk music'), ('Funk', 'Funk'), ('Glam Metal', 'Glam Metal'), ('Gothic', 'Gothic'), ('Grunge', 'Grunge'), ('Hard Rock', 'Hard Rock'), ('Heavy metal', 'Heavy metal'), ('Hip-hop', 'Hip-hop'), ('House', 'House'), ('Indie Rock', 'Indie Rock'), ('Jazz', 'Jazz'), ('Pop', 'Pop'), ('Progressive Rock', 'Progressive Rock'), ('Punk', 'Punk'), ('R&B', 'R&B'), ('Reggae', 'Reggae'), ('Rock', 'Rock'), ('Ska', 'Ska'), ('Soul', 'Soul'), ('Synth-pop', 'Synth-pop'), ('Techno', 'Techno'), ('other', 'other')], default='Alternative Rock', max_length=100),
        ),
    ]
