# Generated by Django 3.2.14 on 2024-06-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_contact_record_location_record_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='created_on',
            new_name='created',
        ),
    ]
