# Generated by Django 3.2.4 on 2024-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_rename_created_on_record_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.CharField(choices=[('alternative-rock', 'Alternative Rock'), ('bachata', 'Bachata'), ('black-metal', 'Black Metal'), ('blues', 'Blues'), ('classical', 'Classical'), ('country', 'Country'), ('dance', 'Dance'), ('death-metal', 'Death Metal'), ('disco', 'Disco'), ('dubstep', 'Dubstep'), ('electronic', 'Electronic'), ('emo', 'Emo'), ('folk-metal', 'Folk metal'), ('folk-music', 'Folk music'), ('funk', 'Funk'), ('glam-metal', 'Glam Metal'), ('gothic', 'Gothic'), ('grunge', 'Grunge'), ('hard-rock', 'Hard Rock'), ('heavy-metal', 'Heavy metal'), ('hip-hop', 'Hip-hop'), ('house', 'House'), ('indie-rock', 'Indie Rock'), ('jazz', 'Jazz'), ('pop', 'Pop'), ('progressive-rock', 'Progressive Rock'), ('punk', 'Punk'), ('r-and-b', 'R&B'), ('reggae', 'Reggae'), ('rock', 'Rock'), ('ska', 'Ska'), ('soul', 'Soul'), ('synth-pop', 'Synth-pop'), ('techno', 'Techno'), ('other', 'other')], default='Alternative Rock', max_length=100),
        ),
    ]
