# Generated by Django 3.2.4 on 2024-07-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('new', 'New'), ('used', 'Used')], default='Good', max_length=9),
        ),
    ]
