# Generated by Django 3.2.4 on 2024-08-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_record_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='released',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
