# Generated by Django 3.2.4 on 2024-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_record_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='track_list',
            new_name='tracklist',
        ),
    ]
